
#yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json

services:
        
  auth-service:
    image: d3k0d/auth-service
    restart: "always" # automatically restart container when server crashes
    ports:
      - "5170:5170" # expose port 3000 so that applications outside the container can connect to it 
      
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - 8432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d app -U app"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - .docker-volumes:/var/lib/postgresql/18/docker
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app

      
  # used for local dev testing of emails from the server
  mailpit:
    image: axllent/mailpit
    profiles:
      - infra
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./.docker-volumes/mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
