# development  | production
env = 'development'

[server]
host = '0.0.0.0'
port = 5170

allowed_origins = ['http://localhost:5173']

[jwt]
cookie_name = 'jwt_auth_token'
secret = 'your_jwt_secret_key_here'
