# development  | production
env = 'development'

[server]
host = '0.0.0.0'
port = 5170

allowed_origins = ['http://localhost:5173']

[jwt]
cookie_name = 'jwt_auth_token'


[jwt.secret]
# type = "raw"
# value = "some string"
#
# or 
#
# type = "ecdsa"
# pub_key = "filepath"
# priv_key = "filepath"
type = "raw"
value = 'change_me'
